base_url = "https://netadr.github.io"
compile_sass = true
build_search_index = false
theme = "hook"

title = "clayton's site"

[markdown]
highlight_code = true

[extra]
links = [
    {title = "GitHub", href = "https://github.com/netadr"},
    {title = "Twitter", href = "https://twitter.com/@netadr_t"},
    {title = "Mastodon", href = "https://infosec.exchange/netadr_t"},
    {title = "Discord", href = "https://discord.com/users/307997003969855488"}
]
