base_url = "https://netadr.github.io"
compile_sass = true
build_search_index = false
theme = "hook"

title = "clayton's site"

[markdown]
highlight_code = true

[extra]
links = [
    {title = "Bluesky", href = "https://bsky.app/profile/straitbizarre.com"},
    {title = "GitHub", href = "https://github.com/netadr"},
    {title = "Discord", href = "https://discord.com/users/307997003969855488"}
]
